---
- name: Install and Configure Apache2
  hosts: K-m
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Configure Apache2 default page
      copy:
        src: Index.html
        dest: /var/www/html/index.html
- name: Install and Configure Nginx
  hosts: K-s
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure Nginx default page
      copy:
        src: Index1.html
        dest: /var/www/html/index.html
